spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: '!ashe4321.'
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect