spring:
  application:
    name: SECURITY
  config:
    activate:
      on-profile: dev
  banner:
    location: banner/dev.txt
  datasource:
    url: jdbc:postgresql://192.168.2.157:5432/test
    username: postgres
    password: '!ashe4321.'
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: 192.168.2.157
    port: 5672
    username: guest
    password: guest
    # confirm模式配置
    publisher-confirm-type: correlated
  # redis 配置
  data:
    redis:
      # 地址
      host: 192.168.2.157
      # 端口  默认为6379
      port: 6379
      # 数据库索引  使用索引为0的数据库
      database: 0
      # 密码 默认无
      password:
      # 连接超时时间
      timeout: 10s
      #   与Jedis相比，lettuce 则完全克服了其线程不安全的缺点.
      #   lettuce 是一个可伸缩的线程安全的Redis客户端，支持同步、异步和响应式模式。
      #   多个线程可以共享一个连接实例， 而不必担心多线程并发问题。
      #   它基于优秀Netty NIO框架构建，支持Redis的更多高级功能。
      lettuce:
        pool:
          # 连接池中的最小空闲连接
          min-idle: 0
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池的最大数据库连接数
          max-active: 8
          # #连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms

# 钉钉登录的AppKey和AppSecret（已加密）
ding-talk:
  app-key: JblFj5f18nZ/kLu/jv3F5GFR+KPn9z+L9VzBzgPkLvk2zLnCHSswD1/rnWQKpknSMY0orOOKJqGWs1WR0Zid7+NKXo3IuIkCCxSi0iP8ey1LRCnxfSsz37UKcke4CktT38IG2YaISPXOUgcx2ffjXGvQbf+gGdNWHzia1cFPnZvmZ/TjZCrRapuTl0pjhhnPeP+jtbVVDG7m1ZIzZSc4404FaXb9RMDu0w/2MpkuF7w/BNRJTC4rQ3t6Gctngfqr9CgYmAMRL6DQpmBZFXz6iTTwXsPrXIuVHKFhk8pINu+Pmsh4BZqBP64eCQUVdGiINOt2trXrwNZrhHSGuywqeA==
  app-secret: MsnOS+P3xcBpUSYRKVMGIMMlCLGQRbX345G7Ov5V1vxSpeKYY4AAsltxzzFGBtCiK8IfIJEfjGciSZIVsi5MZn4Mq/+Bm/f7TwWkJMg09cjecWGrmltmqSeDqlPPAwqOGc3kSqXrtMibm+KS3LiftE13N4u1hfKVJS2C0JX/bCo7sW8NE9kh5J3mdooQDOuHrYo2s6eW94Gkw+yzRqwtst4wlR2byrgz3UpsTIZlNSJh/DBQCF1imG1QQuml99u/fxV32NoHvzWlrQ/mTG79tuhoxbpODcNC/yHHelAv6PhNazdYtu5sM5A7hG4WFr5CXDCnLBZIK9NswXyzNFREFw==

# 固定公钥私钥，用以加密解密敏感信息
rsa:
  public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArVZ9J3YMLbMV3Yl5rexHj4BQg2j1iZkDqcXsWJWOAvoA3uPfgd/WCQgqyTKW1DDQpiyEKZiYGpuzHFxqzTyyGhgAlkk44+Q4hHOM08XTI2WB1KdvJFd1+r0mwl3e1AkJsb6CniK6YJ2ETdoyR7ybnkLgWI/U3q5ZOzRxqu6t3gunF2DENpb5giyD60EjAl4ppzS1qhuUYoiDJjZDdQi5lcpFnw8r36vVdHRTbKeudW088tE2Y6BSwVUp1zwYVdzjP9p3AnvmVTrV3wkbD9yXSiWpBcRNy/0JTTgJ2DYZ38WRpA+ZAl6q0uVFthQwKgjse58QMunKd/IhfcRFbBgVCQIDAQAB
  private_key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCtVn0ndgwtsxXdiXmt7EePgFCDaPWJmQOpxexYlY4C+gDe49+B39YJCCrJMpbUMNCmLIQpmJgam7McXGrNPLIaGACWSTjj5DiEc4zTxdMjZYHUp28kV3X6vSbCXd7UCQmxvoKeIrpgnYRN2jJHvJueQuBYj9Terlk7NHGq7q3eC6cXYMQ2lvmCLIPrQSMCXimnNLWqG5RiiIMmNkN1CLmVykWfDyvfq9V0dFNsp651bTzy0TZjoFLBVSnXPBhV3OM/2ncCe+ZVOtXfCRsP3JdKJakFxE3L/QlNOAnYNhnfxZGkD5kCXqrS5UW2FDAqCOx7nxAy6cp38iF9xEVsGBUJAgMBAAECggEAGYbwtISGg55pnHAYCtyOp1wCv2+QJXzy1KhQx7Tyro6J3Ulay6Iev8LDplC8dLBhse9BYWzXDagbZxRXKDWFlyEsyPUsmycriZoIxdFO6FoVFi+4RvZYah48HIi9faV9F3+Sdd5wazUXXG3DVNw6YMLBjllURJ0RiA4PpVg0I8x+dwtLW3sRgODtT1sCdALwOJVAtdZm4meh16y3kO0uLtkLgVFRB5Efb0j+CfQRLYZKZJhO76r9oXJ7Rr2NgfxcbTYtToseNSagj6z2tnfHdOQhEx+xOvvpIMU533iFqdkEbIEAF2MynB02fa97V835JBHi4g+kZKJ8+RntB7qKLwKBgQDOuuT03GOheYxcqp3mjpaoXUzxC6Ih8i6kczfKPTUhdzQLqrw5oIX9KJiOGSfYOn/REc9IcspNl7w2mMpboKu1hZq+eL890bT/Nq8PcDkvfGdNE1km3f91BVZdmL5f0DdzjbRU7Gv7NCQTYGV22j/DMfU8YzxHEEurEBsEslQeqwKBgQDWpkEZ01N6hEweffC0pZu1Bh9869fQmwPbqtKs5aJcsNzZ92EI5s3qo+9B889TsCO0qjPtVNJTSqueDhTlLtYcCKpcknqNiAXn4/OLf9lbqg2CQTO/G8tdmJKSx4AvPFLQqYCi4wbbnaU16w4lAZwtaUDRkkKKrbDlp+yzabaLGwKBgD3mGf3zK2XDBjMM5yCMmzGoVgxqpk4xvKOC2DaW4xy1G4FOyvMaTGRDzoHlqFeHFJReF8mijU50W2ehkh2jWyaL7YyQjPqOmvo7vmkJ+iVsw2WBoJURrZa1VWnK/V2k86WGzXMMIzzhHNgsadUPfj4M7Ff7gqXojC+ZL+3VE3jnAoGASPFgiCUvZiAVOft0U/8/RaoaAzqmMWasTfbj9wtmPHeB5bRSTlMYwNcK1G/FEdx2lcuNL+a2PsXOQjzozuU2r3omYqUIbpY944qsVciRlbvZMV1090m7t0fE74pKPkMSpYQkibX6u6D75rHFMcA1UZ1GALHiWPwjdDe3kVSoSucCgYAqb4G+egQyt816uDK890Q2rHd8HGul0XHmV+TFAgyfqanKclzMVNz0/w3u2EG1D7H8TOVerjEoETHjuk9H0LlLEiffpnrRbTUgV1NPFgaWWMZuw6Z9SERFySksibqvZOqxDjv7t9lULfNwMNMTN7JYJzbjnFa8OwK5FLjxBypUdw==

# 颁发jwtToken的秘钥（已加密）
oauth2:
  secret-key: OBlgn8rG3lD4L0zrtzYFmuplLXARVekiqrqJ1vi+oIAdS2Eq63GqHgBxmT0Zv45SI8Jlg1xhNxeSvdIpqafTnJioC24ItKWHlbfpwkfQVSxswDm/OOoVWde2fa11119Qgj8mQP+u3ylP87sJqbohZxYqlWu8vKsAlmxYVIH2HmbFyhBpy9QjVMjC4MO41Zo54aC+cHwszyo23EeOO6cMxTWD/BGNe1wPwQgTBcci8AXE4MV5iAogW4/7q1rzuFUrREdQoJsP8mQVFiohSCqkKrUtjJ3wlp3omu1w4O9SYR6ceTEkvLcV8pf0yIwTL2qJaq1hd5SAkgie2YL7ziMgcA==


---
spring:
  application:
    name: SECURITY
  config:
    activate:
      on-profile: test
  banner:
    location: banner/test.txt
  datasource:
    url: jdbc:postgresql://192.168.2.157:5432/test
    username: postgres
    password: '!ashe4321.'
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: 192.168.2.157
    port: 5672
    username: guest
    password: guest
    # confirm模式配置
    publisher-confirm-type: correlated
  # redis 配置
  data:
    redis:
      # 地址
      host: 192.168.2.157
      # 端口  默认为6379
      port: 6379
      # 数据库索引  使用索引为0的数据库
      database: 0
      # 密码 默认无
      password:
      # 连接超时时间
      timeout: 10s
      #   与Jedis相比，lettuce 则完全克服了其线程不安全的缺点.
      #   lettuce 是一个可伸缩的线程安全的Redis客户端，支持同步、异步和响应式模式。
      #   多个线程可以共享一个连接实例， 而不必担心多线程并发问题。
      #   它基于优秀Netty NIO框架构建，支持Redis的更多高级功能。
      lettuce:
        pool:
          # 连接池中的最小空闲连接
          min-idle: 0
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池的最大数据库连接数
          max-active: 8
          # #连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms

# 钉钉登录的AppKey和AppSecret（已加密）
ding-talk:
  app-key: JblFj5f18nZ/kLu/jv3F5GFR+KPn9z+L9VzBzgPkLvk2zLnCHSswD1/rnWQKpknSMY0orOOKJqGWs1WR0Zid7+NKXo3IuIkCCxSi0iP8ey1LRCnxfSsz37UKcke4CktT38IG2YaISPXOUgcx2ffjXGvQbf+gGdNWHzia1cFPnZvmZ/TjZCrRapuTl0pjhhnPeP+jtbVVDG7m1ZIzZSc4404FaXb9RMDu0w/2MpkuF7w/BNRJTC4rQ3t6Gctngfqr9CgYmAMRL6DQpmBZFXz6iTTwXsPrXIuVHKFhk8pINu+Pmsh4BZqBP64eCQUVdGiINOt2trXrwNZrhHSGuywqeA==
  app-secret: MsnOS+P3xcBpUSYRKVMGIMMlCLGQRbX345G7Ov5V1vxSpeKYY4AAsltxzzFGBtCiK8IfIJEfjGciSZIVsi5MZn4Mq/+Bm/f7TwWkJMg09cjecWGrmltmqSeDqlPPAwqOGc3kSqXrtMibm+KS3LiftE13N4u1hfKVJS2C0JX/bCo7sW8NE9kh5J3mdooQDOuHrYo2s6eW94Gkw+yzRqwtst4wlR2byrgz3UpsTIZlNSJh/DBQCF1imG1QQuml99u/fxV32NoHvzWlrQ/mTG79tuhoxbpODcNC/yHHelAv6PhNazdYtu5sM5A7hG4WFr5CXDCnLBZIK9NswXyzNFREFw==

# 固定公钥私钥，用以加密解密敏感信息
rsa:
  public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArVZ9J3YMLbMV3Yl5rexHj4BQg2j1iZkDqcXsWJWOAvoA3uPfgd/WCQgqyTKW1DDQpiyEKZiYGpuzHFxqzTyyGhgAlkk44+Q4hHOM08XTI2WB1KdvJFd1+r0mwl3e1AkJsb6CniK6YJ2ETdoyR7ybnkLgWI/U3q5ZOzRxqu6t3gunF2DENpb5giyD60EjAl4ppzS1qhuUYoiDJjZDdQi5lcpFnw8r36vVdHRTbKeudW088tE2Y6BSwVUp1zwYVdzjP9p3AnvmVTrV3wkbD9yXSiWpBcRNy/0JTTgJ2DYZ38WRpA+ZAl6q0uVFthQwKgjse58QMunKd/IhfcRFbBgVCQIDAQAB
  private_key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCtVn0ndgwtsxXdiXmt7EePgFCDaPWJmQOpxexYlY4C+gDe49+B39YJCCrJMpbUMNCmLIQpmJgam7McXGrNPLIaGACWSTjj5DiEc4zTxdMjZYHUp28kV3X6vSbCXd7UCQmxvoKeIrpgnYRN2jJHvJueQuBYj9Terlk7NHGq7q3eC6cXYMQ2lvmCLIPrQSMCXimnNLWqG5RiiIMmNkN1CLmVykWfDyvfq9V0dFNsp651bTzy0TZjoFLBVSnXPBhV3OM/2ncCe+ZVOtXfCRsP3JdKJakFxE3L/QlNOAnYNhnfxZGkD5kCXqrS5UW2FDAqCOx7nxAy6cp38iF9xEVsGBUJAgMBAAECggEAGYbwtISGg55pnHAYCtyOp1wCv2+QJXzy1KhQx7Tyro6J3Ulay6Iev8LDplC8dLBhse9BYWzXDagbZxRXKDWFlyEsyPUsmycriZoIxdFO6FoVFi+4RvZYah48HIi9faV9F3+Sdd5wazUXXG3DVNw6YMLBjllURJ0RiA4PpVg0I8x+dwtLW3sRgODtT1sCdALwOJVAtdZm4meh16y3kO0uLtkLgVFRB5Efb0j+CfQRLYZKZJhO76r9oXJ7Rr2NgfxcbTYtToseNSagj6z2tnfHdOQhEx+xOvvpIMU533iFqdkEbIEAF2MynB02fa97V835JBHi4g+kZKJ8+RntB7qKLwKBgQDOuuT03GOheYxcqp3mjpaoXUzxC6Ih8i6kczfKPTUhdzQLqrw5oIX9KJiOGSfYOn/REc9IcspNl7w2mMpboKu1hZq+eL890bT/Nq8PcDkvfGdNE1km3f91BVZdmL5f0DdzjbRU7Gv7NCQTYGV22j/DMfU8YzxHEEurEBsEslQeqwKBgQDWpkEZ01N6hEweffC0pZu1Bh9869fQmwPbqtKs5aJcsNzZ92EI5s3qo+9B889TsCO0qjPtVNJTSqueDhTlLtYcCKpcknqNiAXn4/OLf9lbqg2CQTO/G8tdmJKSx4AvPFLQqYCi4wbbnaU16w4lAZwtaUDRkkKKrbDlp+yzabaLGwKBgD3mGf3zK2XDBjMM5yCMmzGoVgxqpk4xvKOC2DaW4xy1G4FOyvMaTGRDzoHlqFeHFJReF8mijU50W2ehkh2jWyaL7YyQjPqOmvo7vmkJ+iVsw2WBoJURrZa1VWnK/V2k86WGzXMMIzzhHNgsadUPfj4M7Ff7gqXojC+ZL+3VE3jnAoGASPFgiCUvZiAVOft0U/8/RaoaAzqmMWasTfbj9wtmPHeB5bRSTlMYwNcK1G/FEdx2lcuNL+a2PsXOQjzozuU2r3omYqUIbpY944qsVciRlbvZMV1090m7t0fE74pKPkMSpYQkibX6u6D75rHFMcA1UZ1GALHiWPwjdDe3kVSoSucCgYAqb4G+egQyt816uDK890Q2rHd8HGul0XHmV+TFAgyfqanKclzMVNz0/w3u2EG1D7H8TOVerjEoETHjuk9H0LlLEiffpnrRbTUgV1NPFgaWWMZuw6Z9SERFySksibqvZOqxDjv7t9lULfNwMNMTN7JYJzbjnFa8OwK5FLjxBypUdw==

# 颁发jwtToken的秘钥（已加密）
oauth2:
  secret-key: OBlgn8rG3lD4L0zrtzYFmuplLXARVekiqrqJ1vi+oIAdS2Eq63GqHgBxmT0Zv45SI8Jlg1xhNxeSvdIpqafTnJioC24ItKWHlbfpwkfQVSxswDm/OOoVWde2fa11119Qgj8mQP+u3ylP87sJqbohZxYqlWu8vKsAlmxYVIH2HmbFyhBpy9QjVMjC4MO41Zo54aC+cHwszyo23EeOO6cMxTWD/BGNe1wPwQgTBcci8AXE4MV5iAogW4/7q1rzuFUrREdQoJsP8mQVFiohSCqkKrUtjJ3wlp3omu1w4O9SYR6ceTEkvLcV8pf0yIwTL2qJaq1hd5SAkgie2YL7ziMgcA==

---
spring:
  application:
    name: SECURITY
  config:
    activate:
      on-profile: prod
  banner:
    location: banner/prod.txt
  datasource:
    url: jdbc:postgresql://192.168.2.157:5432/test
    username: postgres
    password: '!ashe4321.'
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: 192.168.2.157
    port: 5672
    username: guest
    password: guest
    # confirm模式配置
    publisher-confirm-type: correlated
  # redis 配置
  data:
    redis:
      # 地址
      host: 192.168.2.157
      # 端口  默认为6379
      port: 6379
      # 数据库索引  使用索引为0的数据库
      database: 0
      # 密码 默认无
      password:
      # 连接超时时间
      timeout: 10s
      #   与Jedis相比，lettuce 则完全克服了其线程不安全的缺点.
      #   lettuce 是一个可伸缩的线程安全的Redis客户端，支持同步、异步和响应式模式。
      #   多个线程可以共享一个连接实例， 而不必担心多线程并发问题。
      #   它基于优秀Netty NIO框架构建，支持Redis的更多高级功能。
      lettuce:
        pool:
          # 连接池中的最小空闲连接
          min-idle: 0
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池的最大数据库连接数
          max-active: 8
          # #连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms

# 钉钉登录的AppKey和AppSecret（已加密）
ding-talk:
  app-key: JblFj5f18nZ/kLu/jv3F5GFR+KPn9z+L9VzBzgPkLvk2zLnCHSswD1/rnWQKpknSMY0orOOKJqGWs1WR0Zid7+NKXo3IuIkCCxSi0iP8ey1LRCnxfSsz37UKcke4CktT38IG2YaISPXOUgcx2ffjXGvQbf+gGdNWHzia1cFPnZvmZ/TjZCrRapuTl0pjhhnPeP+jtbVVDG7m1ZIzZSc4404FaXb9RMDu0w/2MpkuF7w/BNRJTC4rQ3t6Gctngfqr9CgYmAMRL6DQpmBZFXz6iTTwXsPrXIuVHKFhk8pINu+Pmsh4BZqBP64eCQUVdGiINOt2trXrwNZrhHSGuywqeA==
  app-secret: MsnOS+P3xcBpUSYRKVMGIMMlCLGQRbX345G7Ov5V1vxSpeKYY4AAsltxzzFGBtCiK8IfIJEfjGciSZIVsi5MZn4Mq/+Bm/f7TwWkJMg09cjecWGrmltmqSeDqlPPAwqOGc3kSqXrtMibm+KS3LiftE13N4u1hfKVJS2C0JX/bCo7sW8NE9kh5J3mdooQDOuHrYo2s6eW94Gkw+yzRqwtst4wlR2byrgz3UpsTIZlNSJh/DBQCF1imG1QQuml99u/fxV32NoHvzWlrQ/mTG79tuhoxbpODcNC/yHHelAv6PhNazdYtu5sM5A7hG4WFr5CXDCnLBZIK9NswXyzNFREFw==

# 固定公钥私钥，用以加密解密敏感信息
rsa:
  public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArVZ9J3YMLbMV3Yl5rexHj4BQg2j1iZkDqcXsWJWOAvoA3uPfgd/WCQgqyTKW1DDQpiyEKZiYGpuzHFxqzTyyGhgAlkk44+Q4hHOM08XTI2WB1KdvJFd1+r0mwl3e1AkJsb6CniK6YJ2ETdoyR7ybnkLgWI/U3q5ZOzRxqu6t3gunF2DENpb5giyD60EjAl4ppzS1qhuUYoiDJjZDdQi5lcpFnw8r36vVdHRTbKeudW088tE2Y6BSwVUp1zwYVdzjP9p3AnvmVTrV3wkbD9yXSiWpBcRNy/0JTTgJ2DYZ38WRpA+ZAl6q0uVFthQwKgjse58QMunKd/IhfcRFbBgVCQIDAQAB
  private_key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCtVn0ndgwtsxXdiXmt7EePgFCDaPWJmQOpxexYlY4C+gDe49+B39YJCCrJMpbUMNCmLIQpmJgam7McXGrNPLIaGACWSTjj5DiEc4zTxdMjZYHUp28kV3X6vSbCXd7UCQmxvoKeIrpgnYRN2jJHvJueQuBYj9Terlk7NHGq7q3eC6cXYMQ2lvmCLIPrQSMCXimnNLWqG5RiiIMmNkN1CLmVykWfDyvfq9V0dFNsp651bTzy0TZjoFLBVSnXPBhV3OM/2ncCe+ZVOtXfCRsP3JdKJakFxE3L/QlNOAnYNhnfxZGkD5kCXqrS5UW2FDAqCOx7nxAy6cp38iF9xEVsGBUJAgMBAAECggEAGYbwtISGg55pnHAYCtyOp1wCv2+QJXzy1KhQx7Tyro6J3Ulay6Iev8LDplC8dLBhse9BYWzXDagbZxRXKDWFlyEsyPUsmycriZoIxdFO6FoVFi+4RvZYah48HIi9faV9F3+Sdd5wazUXXG3DVNw6YMLBjllURJ0RiA4PpVg0I8x+dwtLW3sRgODtT1sCdALwOJVAtdZm4meh16y3kO0uLtkLgVFRB5Efb0j+CfQRLYZKZJhO76r9oXJ7Rr2NgfxcbTYtToseNSagj6z2tnfHdOQhEx+xOvvpIMU533iFqdkEbIEAF2MynB02fa97V835JBHi4g+kZKJ8+RntB7qKLwKBgQDOuuT03GOheYxcqp3mjpaoXUzxC6Ih8i6kczfKPTUhdzQLqrw5oIX9KJiOGSfYOn/REc9IcspNl7w2mMpboKu1hZq+eL890bT/Nq8PcDkvfGdNE1km3f91BVZdmL5f0DdzjbRU7Gv7NCQTYGV22j/DMfU8YzxHEEurEBsEslQeqwKBgQDWpkEZ01N6hEweffC0pZu1Bh9869fQmwPbqtKs5aJcsNzZ92EI5s3qo+9B889TsCO0qjPtVNJTSqueDhTlLtYcCKpcknqNiAXn4/OLf9lbqg2CQTO/G8tdmJKSx4AvPFLQqYCi4wbbnaU16w4lAZwtaUDRkkKKrbDlp+yzabaLGwKBgD3mGf3zK2XDBjMM5yCMmzGoVgxqpk4xvKOC2DaW4xy1G4FOyvMaTGRDzoHlqFeHFJReF8mijU50W2ehkh2jWyaL7YyQjPqOmvo7vmkJ+iVsw2WBoJURrZa1VWnK/V2k86WGzXMMIzzhHNgsadUPfj4M7Ff7gqXojC+ZL+3VE3jnAoGASPFgiCUvZiAVOft0U/8/RaoaAzqmMWasTfbj9wtmPHeB5bRSTlMYwNcK1G/FEdx2lcuNL+a2PsXOQjzozuU2r3omYqUIbpY944qsVciRlbvZMV1090m7t0fE74pKPkMSpYQkibX6u6D75rHFMcA1UZ1GALHiWPwjdDe3kVSoSucCgYAqb4G+egQyt816uDK890Q2rHd8HGul0XHmV+TFAgyfqanKclzMVNz0/w3u2EG1D7H8TOVerjEoETHjuk9H0LlLEiffpnrRbTUgV1NPFgaWWMZuw6Z9SERFySksibqvZOqxDjv7t9lULfNwMNMTN7JYJzbjnFa8OwK5FLjxBypUdw==

# 颁发jwtToken的秘钥（已加密）
oauth2:
  secret-key: OBlgn8rG3lD4L0zrtzYFmuplLXARVekiqrqJ1vi+oIAdS2Eq63GqHgBxmT0Zv45SI8Jlg1xhNxeSvdIpqafTnJioC24ItKWHlbfpwkfQVSxswDm/OOoVWde2fa11119Qgj8mQP+u3ylP87sJqbohZxYqlWu8vKsAlmxYVIH2HmbFyhBpy9QjVMjC4MO41Zo54aC+cHwszyo23EeOO6cMxTWD/BGNe1wPwQgTBcci8AXE4MV5iAogW4/7q1rzuFUrREdQoJsP8mQVFiohSCqkKrUtjJ3wlp3omu1w4O9SYR6ceTEkvLcV8pf0yIwTL2qJaq1hd5SAkgie2YL7ziMgcA==
