spring:
  application:
    name: SECURITY
  config:
    activate:
      on-profile: dev
  banner:
    location: banner/dev.txt
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: '!ashe4321.'
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: 192.168.2.157
    port: 5672
    username: guest
    password: guest
    # confirm模式配置
    publisher-confirm-type: correlated

# 钉钉登录的AppKey和AppSecret（已加密）
ding-talk:
  app-key: JblFj5f18nZ/kLu/jv3F5GFR+KPn9z+L9VzBzgPkLvk2zLnCHSswD1/rnWQKpknSMY0orOOKJqGWs1WR0Zid7+NKXo3IuIkCCxSi0iP8ey1LRCnxfSsz37UKcke4CktT38IG2YaISPXOUgcx2ffjXGvQbf+gGdNWHzia1cFPnZvmZ/TjZCrRapuTl0pjhhnPeP+jtbVVDG7m1ZIzZSc4404FaXb9RMDu0w/2MpkuF7w/BNRJTC4rQ3t6Gctngfqr9CgYmAMRL6DQpmBZFXz6iTTwXsPrXIuVHKFhk8pINu+Pmsh4BZqBP64eCQUVdGiINOt2trXrwNZrhHSGuywqeA==
  app-secret: MsnOS+P3xcBpUSYRKVMGIMMlCLGQRbX345G7Ov5V1vxSpeKYY4AAsltxzzFGBtCiK8IfIJEfjGciSZIVsi5MZn4Mq/+Bm/f7TwWkJMg09cjecWGrmltmqSeDqlPPAwqOGc3kSqXrtMibm+KS3LiftE13N4u1hfKVJS2C0JX/bCo7sW8NE9kh5J3mdooQDOuHrYo2s6eW94Gkw+yzRqwtst4wlR2byrgz3UpsTIZlNSJh/DBQCF1imG1QQuml99u/fxV32NoHvzWlrQ/mTG79tuhoxbpODcNC/yHHelAv6PhNazdYtu5sM5A7hG4WFr5CXDCnLBZIK9NswXyzNFREFw==

# 固定公钥私钥，用以加密解密敏感信息
rsa:
  public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArVZ9J3YMLbMV3Yl5rexHj4BQg2j1iZkDqcXsWJWOAvoA3uPfgd/WCQgqyTKW1DDQpiyEKZiYGpuzHFxqzTyyGhgAlkk44+Q4hHOM08XTI2WB1KdvJFd1+r0mwl3e1AkJsb6CniK6YJ2ETdoyR7ybnkLgWI/U3q5ZOzRxqu6t3gunF2DENpb5giyD60EjAl4ppzS1qhuUYoiDJjZDdQi5lcpFnw8r36vVdHRTbKeudW088tE2Y6BSwVUp1zwYVdzjP9p3AnvmVTrV3wkbD9yXSiWpBcRNy/0JTTgJ2DYZ38WRpA+ZAl6q0uVFthQwKgjse58QMunKd/IhfcRFbBgVCQIDAQAB
  private_key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCtVn0ndgwtsxXdiXmt7EePgFCDaPWJmQOpxexYlY4C+gDe49+B39YJCCrJMpbUMNCmLIQpmJgam7McXGrNPLIaGACWSTjj5DiEc4zTxdMjZYHUp28kV3X6vSbCXd7UCQmxvoKeIrpgnYRN2jJHvJueQuBYj9Terlk7NHGq7q3eC6cXYMQ2lvmCLIPrQSMCXimnNLWqG5RiiIMmNkN1CLmVykWfDyvfq9V0dFNsp651bTzy0TZjoFLBVSnXPBhV3OM/2ncCe+ZVOtXfCRsP3JdKJakFxE3L/QlNOAnYNhnfxZGkD5kCXqrS5UW2FDAqCOx7nxAy6cp38iF9xEVsGBUJAgMBAAECggEAGYbwtISGg55pnHAYCtyOp1wCv2+QJXzy1KhQx7Tyro6J3Ulay6Iev8LDplC8dLBhse9BYWzXDagbZxRXKDWFlyEsyPUsmycriZoIxdFO6FoVFi+4RvZYah48HIi9faV9F3+Sdd5wazUXXG3DVNw6YMLBjllURJ0RiA4PpVg0I8x+dwtLW3sRgODtT1sCdALwOJVAtdZm4meh16y3kO0uLtkLgVFRB5Efb0j+CfQRLYZKZJhO76r9oXJ7Rr2NgfxcbTYtToseNSagj6z2tnfHdOQhEx+xOvvpIMU533iFqdkEbIEAF2MynB02fa97V835JBHi4g+kZKJ8+RntB7qKLwKBgQDOuuT03GOheYxcqp3mjpaoXUzxC6Ih8i6kczfKPTUhdzQLqrw5oIX9KJiOGSfYOn/REc9IcspNl7w2mMpboKu1hZq+eL890bT/Nq8PcDkvfGdNE1km3f91BVZdmL5f0DdzjbRU7Gv7NCQTYGV22j/DMfU8YzxHEEurEBsEslQeqwKBgQDWpkEZ01N6hEweffC0pZu1Bh9869fQmwPbqtKs5aJcsNzZ92EI5s3qo+9B889TsCO0qjPtVNJTSqueDhTlLtYcCKpcknqNiAXn4/OLf9lbqg2CQTO/G8tdmJKSx4AvPFLQqYCi4wbbnaU16w4lAZwtaUDRkkKKrbDlp+yzabaLGwKBgD3mGf3zK2XDBjMM5yCMmzGoVgxqpk4xvKOC2DaW4xy1G4FOyvMaTGRDzoHlqFeHFJReF8mijU50W2ehkh2jWyaL7YyQjPqOmvo7vmkJ+iVsw2WBoJURrZa1VWnK/V2k86WGzXMMIzzhHNgsadUPfj4M7Ff7gqXojC+ZL+3VE3jnAoGASPFgiCUvZiAVOft0U/8/RaoaAzqmMWasTfbj9wtmPHeB5bRSTlMYwNcK1G/FEdx2lcuNL+a2PsXOQjzozuU2r3omYqUIbpY944qsVciRlbvZMV1090m7t0fE74pKPkMSpYQkibX6u6D75rHFMcA1UZ1GALHiWPwjdDe3kVSoSucCgYAqb4G+egQyt816uDK890Q2rHd8HGul0XHmV+TFAgyfqanKclzMVNz0/w3u2EG1D7H8TOVerjEoETHjuk9H0LlLEiffpnrRbTUgV1NPFgaWWMZuw6Z9SERFySksibqvZOqxDjv7t9lULfNwMNMTN7JYJzbjnFa8OwK5FLjxBypUdw==

# 颁发jwtToken的私钥
oauth2:
  secret-key: 6D5970337336763979244226452948404D635166546A576E5A7234743777217A


---
spring:
  application:
    name: SECURITY
  config:
    activate:
      on-profile: test
  banner:
    location: banner/test.txt
  datasource:
    url: jdbc:postgresql://192.168.2.157:5432/test
    username: postgres
    password: '!ashe4321.'
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

ding-talk:
  app-key: xxx
  app-secret: xxx

# 颁发jwtToken的私钥
oauth2:
  secret-key: 6D5970337336763979244226452948404D635166546A576E5A7234743777217A
---
spring:
  application:
    name: SECURITY
  config:
    activate:
      on-profile: prod
  banner:
    location: banner/prod.txt
  datasource:
    url: jdbc:postgresql://192.168.2.157:5432/test
    username: postgres
    password: '!ashe4321.'
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

ding-talk:
  app-key: xxx
  app-secret: xxx

# 颁发jwtToken的私钥
oauth2:
  secret-key: 6D5970337336763979244226452948404D635166546A576E5A7234743777217A