### 1、注册用户
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "mobile": "15283871282",
  "password": "1234",
  "firstname": "Ashe",
  "lastname": "Red"
}

### 2、账号登录

POST http://localhost:8080/api/v1/auth/authenticate
Content-Type: application/json

{
  "mobile": "15283871282",
  "password": "1234"
}

### 3、手机验证码登录

POST http://localhost:8080/api/v1/auth/code/xxxx


### 4、钉钉扫码登录

http://127.0.0.1:8080/code.html


### 5、根据令牌访问权限接口

# 以上接口都会返回token，此后携带token访问需要鉴权的接口
GET http://localhost:8080/api/v1/token/welcome
Authorization: Bearer xxxx

